openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Arch Lab Example API'
  description: Пример API для первого домашнего задания по курсу Архитектура программных систем
servers:
  - url: http://192.168.64.6
    description: Sample server
paths:
  /search:
    get:
      summary: Search authors by mask of first name and last name
      parameters:
      - name: first_name
        description: Имя
        in: query
        required: true
        schema:
          type: string
      - name: last_name
        description: Фамилия
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The authors corresponding to the provided masks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authors'
        404:
          description: No author found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /author:
    get:
      summary: Read a author information
      parameters:
      - name: id
        description: Уникальный идентификатор автора
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/author_id'
      responses:
        '200':
          description: The author corresponding to the provided `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/author'
        404:
          description: No author found for the provided `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Add author information
      parameters:
      - name: first_name
        description: Имя автора
        in: query
        required: true
        schema:
          type: string
      - name: last_name
        description: Фамилия автора
        in: query
        required: true
        schema:
          type: string
      - name: email
        description: email автора
        in: query
        required: true
        schema:
          type: string
      - name: title
        description: Форма обращение к автору 
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Идентификатор, добавленного автора
          content:
            application/json:
              schema:
                type: integer
        404:
          description: No author found for the provided `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    author_id:
      description: Уникальный идентификатор автора
      type: integer
    authors:
      type: array
      items:
        $ref: '#/components/schemas/author'
    author:
      type: object
      required:
        - id
        - first_name
        - last_name
        - email
        - title
      properties:
        id:
          $ref: '#/components/schemas/author_id'
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        title:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string